---
- name: "Place config file."
  ansible.builtin.template:
    src: "minio.default.j2"
    dest: "/etc/default/minio"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "Restart {{ role_name }}."

- name: "Check for credentials file."
  ansible.builtin.stat:
    path: "/etc/default/minioadmin"
  register: "stat_minio_creds"

- name: "Generate root credentials file."
  when: "not stat_minio_creds.stat.exists"
  block:
    - name: "Generate root username."
      when:
        - "minio_root_username is undefined"
        - "minio_root_generate_credentials | bool"
      ansible.builtin.set_fact:
        minio_root_username: "minioadmin-{{ lookup('community.general.random_string', upper=false, special=false) }}"

    - name: "Generate root password."
      when:
        - "minio_root_password is undefined"
        - "minio_root_generate_credentials | bool"
      ansible.builtin.set_fact:
        minio_root_password: "{{ lookup('community.general.random_string', length=48, min_lower=1, min_upper=1, min_numeric=1, special=false) }}"

    - name: "Place credentials config file."
      ansible.builtin.template:
        src: "minioadmin.default.j2"
        dest: "/etc/default/minioadmin"
        owner: "root"
        group: "root"
        mode: "0640"
      notify: "Restart {{ role_name }}."

- name: "Copy credentials file to cluster nodes."
  when:
    - "minio_is_cluster_member"
    - "minio_root_generate_credentials"
    - "groups[minio_cluster_group_name].index(inventory_hostname) != 0"
  block:
    - name: "Fetch credentials from first node."
      ansible.builtin.slurp:
        path: "/etc/default/minioadmin"
      register: "minioadmin_credentials"
      delegate_to: "{{ groups[minio_cluster_group_name] | first }}"

    - name: "Distribute credentials to other nodes."
      ansible.builtin.copy:
        content: "{{ minioadmin_credentials.content | b64decode }}"
        dest: "/etc/default/minioadmin"
        owner: "root"
        group: "root"
        mode: "0640"
      notify: "Restart {{ role_name }}."

- name: "Setup TLS."
  when: "minio_tls_enabled | bool"
  block:
    - name: "Create certs dir."
      ansible.builtin.file:
        path: "{{ minio_config_dir }}/.minio/certs"
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
        mode: "0750"
        state: "directory"

    - name: "Copy TLS files."
      ansible.builtin.copy:
        content: |
          {{ item.content }}
        dest: "{{ minio_config_dir }}/.minio/certs/{{ item.filename }}"
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
        mode: "0440"
      loop:
        - content: "{{ minio_tls_certificate_content }}"
          filename: "public.crt"
        - content: "{{ minio_tls_private_key_content }}"
          filename: "private.key"
      loop_control:
        label: "{{ item.filename }}"
      notify: "Restart {{ role_name }}."

    - name: "Setup custom CA."
      when: "minio_tls_ca_content is defined"
      block:
        - name: "Create CA dir."
          ansible.builtin.file:
            path: "{{ minio_config_dir }}/.minio/certs/CAs"
            owner: "{{ minio_user }}"
            group: "{{ minio_group }}"
            mode: "0750"
            state: "directory"

        - name: "Copy custom CA."
          ansible.builtin.copy:
            content: |
              {{ minio_tls_ca_content }}
            dest: "{{ minio_config_dir }}/.minio/certs/CAs/myCA.crt"
            owner: "{{ minio_user }}"
            group: "{{ minio_group }}"
            mode: "0440"
          notify: "Restart {{ role_name }}."
