---
- name: "Import variables tasks."
  ansible.builtin.import_tasks: "set_vars.yml"

- name: "Import preflight tasks."
  ansible.builtin.import_tasks: "preflight.yml"

- name: "Import server setup tasks."
  ansible.builtin.import_tasks: "setup.yml"

- name: "Import client setup tasks."
  when: "minio_client_installed"
  ansible.builtin.include_tasks: "setup-client.yml"

- name: "Import configure tasks."
  ansible.builtin.import_tasks: "configure.yml"

- name: "Import service tasks."
  ansible.builtin.import_tasks: "service.yml"

- name: "Flush handlers."
  ansible.builtin.meta: "flush_handlers"
