---
- name: "Create system group."
  ansible.builtin.group:
    name: "{{ minio_group }}"
    system: true
    state: "present"

- name: "Create system user."
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true
    create_home: false
    home: "{{ minio_config_dir }}"
    shell: "/sbin/nologin"
    state: "present"

- name: "Create data dirs." # noqa risky-file-permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
  loop: "{{ minio_volumes }}"

- name: "Set permissions on data dirs."
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"
    state: "directory"
  loop: "{{ minio_volumes }}"

- name: "Create config dir."
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"
    state: "directory"
  loop:
    - "{{ minio_config_dir }}"
    - "{{ minio_config_dir }}/.minio"
