---
- name: "Verify."
  hosts: "all"
  tasks:
    - name: "Check if service is live via Healthcheck API."
      ansible.builtin.uri:
        url: "https://localhost:9000/minio/health/live"
        method: "GET"
        follow_redirects: "none"
        ca_path: "/opt/minio/.minio/certs/CAs/myCA.crt"
        validate_certs: true
